### ISSUE TITLE
Discovered ports not persisting after refresh

### ISSUE THREAD

**Issue by boyuanx** [corpnewt/USBMap#15]
As the title suggests, in the new version the discovered ports fail to persist after unplugging the device. Works fine in the old version.

**Comment by corpnewt** [comment]
If I'm understanding your issue, you're stating that when in discovery, if you plug in a device it shows, and then unplugging it removes it from the list, correct?  This is by design.

There was an issue with the port counts only referencing the populated ports per controller at that current time - not the *total* populate ports per controller during discovery.  That has been corrected in [this commit](https://github.com/corpnewt/USBMap/commit/ea836d2b6341b44ff2f890fdedb1200be78a7268).

-CorpNewt
